<?php	return array (
  '/^spend\\/(\\d+)\\/(\\d+)/' => 'Spend/lists?user_account=:1&spend_ip=:2',
  'promote$' => 'Home/Promote/index',
  'opgm/:game_id' => 'Media/Game/open_game',
  'detail/:id' => 'Media/Game/detail',
  'index$' => 'Media/Index/index',
  'game$' => 'Media/Game/index',
  'gift$' => 'Media/Gift/index',
  'subscriber$' => 'Media/Subscriber/index',
  'gamehot$' => 'Media/Game/game_hot',
  'gmgf/:game_id' => 'Media/Gift/game_gift',
  'server$' => 'Media/Gift/server',
  'huodong$' => 'Media/Gift/huodong',
  'giftde/:gift_id/:game_id' => 'Media/Gift/detail',
  'huodongde/:id' => 'Media/Gift/huodong_detail',
  'gamesort$' => 'Media/Game/game_sort',
  'gmstde/:game_type_id' => 'Media/Game/game_sort_detail',
  'newde/:id' => 'Media/News/detail',
  'bdptb/:id' => 'Media/Subscriber/bdptb',
  'mygame/:type' => 'Media/Subscriber/my_game',
  'mygift$' => 'Media/Subscriber/my_gift',
  'subacc$' => 'Media/Subscriber/account',
  'subcon$' => 'Media/Subscriber/contact',
  'subfeed$' => 'Media/Subscriber/feedback',
  'subfindpwd$' => 'Media/Subscriber/u_findpwd_1',
  'subfindpwd3$' => 'Media/Subscriber/u_findpwd_3',
  'subfindpwd4$' => 'Media/Subscriber/u_findpwd_4',
  'subpay$' => 'Media/Subscriber/pay',
  ' 	login$' => 'Media/Subscriber/login',
  'subagr$' => 'Media/Subscriber/agreement',
  'subreg$' => 'Media/Subscriber/register',
  'news$' => 'Media/Gift/news',
  'subfindpwd2$' => 'Media/Subscriber/u_findpwd_2',
  'subagre' => 'Media/Subscriber/agreement',
);